/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import paquetegrafo.Grafo;
        
/**
 *
 * @author aiannelli
 */

public class Ventana2 extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Ventana2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ValorT = new javax.swing.JTextField();
        CambiarValorT = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        AgregarLinea = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ValorUbicacionSucursal = new javax.swing.JTextField();
        ImprimirUbicacionesJSON = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ColocarSucursal = new javax.swing.JButton();
        RevisarCoberturaTotal = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        MostrarGrafo = new javax.swing.JButton();
        RevisarCoberturaSucursal1 = new javax.swing.JButton();
        Exit2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 93, -1, -1));
        getContentPane().add(ValorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 170, -1));

        CambiarValorT.setText("Cambiar valor de T");
        CambiarValorT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CambiarValorTActionPerformed(evt);
            }
        });
        getContentPane().add(CambiarValorT, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel2.setText("Indique el valor de t:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        AgregarLinea.setText("Agregar línea");
        AgregarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarLineaActionPerformed(evt);
            }
        });
        getContentPane().add(AgregarLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel3.setText("Las ubicaciones posibles para colocar una sucursal son las siguientes:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 410, 40));

        ValorUbicacionSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorUbicacionSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(ValorUbicacionSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 200, -1));

        ImprimirUbicacionesJSON.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImprimirUbicacionesJSONActionPerformed(evt);
            }
        });
        getContentPane().add(ImprimirUbicacionesJSON, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 510, 70));

        jLabel4.setText("Indique la ubicación de la sucursal:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 190, 40));

        ColocarSucursal.setText("Colocar sucursal");
        ColocarSucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColocarSucursalActionPerformed(evt);
            }
        });
        getContentPane().add(ColocarSucursal, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, -1, -1));

        RevisarCoberturaTotal.setText("Revisar cobertura total");
        RevisarCoberturaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevisarCoberturaTotalActionPerformed(evt);
            }
        });
        getContentPane().add(RevisarCoberturaTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        jLabel5.setText("En el caso de querer agregar una línea por favor suba el archivo .JSON con la información de las paradas de la misma:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        MostrarGrafo.setText("Mostrar Red de Transporte");
        getContentPane().add(MostrarGrafo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        RevisarCoberturaSucursal1.setText("Revisar cobertura");
        RevisarCoberturaSucursal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevisarCoberturaSucursal1ActionPerformed(evt);
            }
        });
        getContentPane().add(RevisarCoberturaSucursal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        Exit2.setText("X");
        Exit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit2ActionPerformed(evt);
            }
        });
        getContentPane().add(Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CambiarValorTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CambiarValorTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CambiarValorTActionPerformed

    private void AgregarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarLineaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgregarLineaActionPerformed

    private void ImprimirUbicacionesJSONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ImprimirUbicacionesJSONActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ImprimirUbicacionesJSONActionPerformed

    private void ValorUbicacionSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorUbicacionSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorUbicacionSucursalActionPerformed

    private void ColocarSucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColocarSucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ColocarSucursalActionPerformed

    private void RevisarCoberturaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevisarCoberturaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RevisarCoberturaTotalActionPerformed

    private void RevisarCoberturaSucursal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevisarCoberturaSucursal1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RevisarCoberturaSucursal1ActionPerformed

    private void Exit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarLinea;
    private javax.swing.JButton CambiarValorT;
    private javax.swing.JButton ColocarSucursal;
    private javax.swing.JButton Exit2;
    private javax.swing.JTextField ImprimirUbicacionesJSON;
    private javax.swing.JButton MostrarGrafo;
    private javax.swing.JButton RevisarCoberturaSucursal1;
    private javax.swing.JButton RevisarCoberturaTotal;
    private javax.swing.JTextField ValorT;
    private javax.swing.JTextField ValorUbicacionSucursal;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
